Commands
theforeman/hammer-cli-foreman-virt-who-configure pull request #1
Opened 2017-05-15 12:02 UTC by tstrachota

2017-05-15 12:04 UTC, tstrachota commented
@ares ready for initial review. I'll probably add translating of listing mode from `whitelist/blacklist/none` to numbers.

2017-05-19 11:54 UTC, tstrachota commented
@ares, I pushed the tests and consider the branch to be ready for review now.

2017-05-30 07:02 UTC, ares commented
2 nits found during testing, otherwise looks good :+1:

2017-05-30 07:02 UTC, ares requested changes

2017-05-30 07:02 UTC, ares commented on lib/hammer_cli_foreman_virt_who_configure/config.rb
> +          field :blacklist, _('Filtered hosts'), Fields::Field, :hide_blank => true
I think the translations need to be swapped with whitelist which filters hosts to be parsed, while blacklist excludes hosts

2017-05-30 07:02 UTC, ares commented on lib/hammer_cli_foreman_virt_who_configure/config.rb
> +      action :deploy_script
I guess this causes deploy and fetch script have the same help
``` 
deploy                        Renders a deploy script for the specified virt-who configuration
fetch                         Renders a deploy script for the specified virt-who configuration
```

could deploy script also say it runs the script right away?

2017-05-30 07:45 UTC, tstrachota commented
@ares updated

2017-05-30 10:30 UTC, ares commented
Ack, works nicely and covers it all :+1:, once this gets in, I think we can start moving it under theforeman organization. Probably best to ask on #theforeman-dev irc channel

2017-05-30 11:59 UTC, tstrachota commented
Meerged as https://github.com/tstrachota/hammer-cli-foreman-virt-who-configure/commit/f23454760595b3cf37ab33d4719c418dfa1a25bb and https://github.com/tstrachota/hammer-cli-foreman-virt-who-configure/commit/04ac873b9e27a2ec94947ec9a50f16a4c41640d1

2017-05-30 11:59 UTC, closed without merging