Use Foreman GH Actions
theforeman/hammer-cli-foreman-virt-who-configure pull request #28
Opened 2024-02-27 19:42 UTC by chris1984

2024-03-14 14:11 UTC, ofedoren approved these changes
Thanks, @chris1984, LGTM.

I'd also like to ask you if you could update the `data` for the tests and maybe add GHA for running the test suite as well?

2024-03-25 12:43 UTC, ofedoren requested changes
Thanks, @chris1984 ! LGTM, just some small things inline.

2024-03-25 12:43 UTC, ofedoren commented on hammer_cli_foreman_virt_who_configure.gemspec
> +  s.add_dependency 'hammer_cli_foreman', '~> 3.9'
I'd rather pin for major version change, i.e. `< 4.0` for both...

2024-03-25 12:43 UTC, ofedoren commented on test/functional/config/config_list_test.rb
>          'page' => '2',
Make this a number instead of string and the test should pass.

2024-03-25 16:10 UTC, chris1984 commented
@ofedoren updated. The Ruby 2.7 tests are failing with all kinds of fun non initialized errors, I am wondering if we should just pull Ruby 2.7 out or just leave it as for now?

2024-03-26 11:45 UTC, ofedoren commented
@chris1984 Ruby 2.7 failures due to warnings can be fixed via https://github.com/theforeman/hammer-cli/blob/master/Rakefile#L14. Let's do that and it's ready to go :)

2024-03-26 14:49 UTC, merged